services:
  # Frontend - React with Nginx
  frontend:
    build:
      context: ./infra/nginx
      dockerfile: Dockerfile
      args:
        BUILD_ARGUMENT_ENV: dev
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./software/frontend/dist:/usr/share/nginx/html:ro
      - ./infra/nginx/conf.d/frontend.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/nginx/logs:/var/log/nginx
    depends_on:
      - api
    networks:
      - internal_network

  # API - Nginx for Symfony
  api:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./software/backend/symfony-api:/var/www/html:ro,cached
      - ./software/backend/symfony-api/var/log/nginx:/var/log/nginx
      - ./infra/nginx/conf.d/api.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - internal_network

  # PHP-FPM (Symfony)
  php:
    build:
      context: ./infra/
      dockerfile: ./php/Dockerfile
    volumes:
      - ./software/backend/symfony-api:/var/www/html:cached
      - ./infra/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./infra/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./infra/php/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - database
    networks:
      - internal_network
    expose:
      - "9000"
      - "9003"

  database:
    image: mysql
    platform: linux/x86_64
    command: --innodb-use-native-aio=${INNODB_USE_NATIVE_AIO:-1} --sql_mode=${SQL_MODE:-"ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"}
    environment:
      MYSQL_DATABASE: egoodies
      MYSQL_ROOT_PASSWORD: e47goodies@anam
    ports:
      - "33060:3306"
    volumes:
      - mysql_user:/var/lib/mysql:delegated
    networks:
      - internal_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: database
    ports:
      - "9002:80"
    depends_on:
      - database
    networks:
      - internal_network
    volumes:
      - db_admin_data:/var/www/html

volumes:
  db_admin_data:
  mysql:
  mysql_user:

networks:
  internal_network:
    name: internal_network